// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tasked.Server.Context;

namespace Tasked.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Tasked.Shared.Data.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Effort")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Works");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d23a1f89-4f41-4870-bb1f-2d72d401e638"),
                            Effort = 5,
                            Name = "Tarefa 1"
                        },
                        new
                        {
                            Id = new Guid("3e368b56-3942-47b3-a11b-d273ae3d3dd9"),
                            Effort = 1,
                            Name = "Tarefa 2"
                        },
                        new
                        {
                            Id = new Guid("50bbbbc8-3e75-4260-8a04-fddccbccba5d"),
                            Effort = 10,
                            Name = "Tarefa 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
